services:
  oracle-db:
    image: gvenzl/oracle-xe:11.2.0.2-full
    container_name: oracle_db_RM565206
    shm_size: 1gb
    networks:
      - aegis-network
    environment:
      - ORACLE_PASSWORD=200806 # Variável de ambiente obrigatória
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/u01/app/oracle # Volume nomeado para persistência
    restart: unless-stopped

  api:
    build: . # Gera imagem personalizada
    container_name: api_aegis_RM565206
    networks:
      - aegis-network
    environment:
      - ConnectionStrings__OracleConnection=User Id=system;Password=200806;Data Source=oracle-db:1521/xe
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  aegis-network:
    driver: bridge

volumes:
  oracle_data: # Declaração do volume nomeado